### ISSUE TITLE
After editing a layout you can't edit another one until a page refres

### ISSUE THREAD

**Issue by nico-vromans** [ceoloide/ergogen-gui#3]
When you switch to another layout (or the one already loaded), whenever you edit this layout, it almost instantly resets. The cursor jumps to the bottom of the file, and whatever characters you type (or edits you make) thereafter almost instantly disappear (the file resets).
Only a refresh seems to "unlock" the layout again.
Checking (or unchecking) any of the checkboxes ("Auto-generate", "Debug", "Auto-gen PCB, 3D") doesn't seem to change anything.

It seems something happens whenever the filename is shown in the top dropdown that prevents editing, so you have to select the example you want to edit and refresh the page to be able to edit without the file resetting (this clears the dropdown).

I've tested this on both https://ergogen.ceoloide.com/ and have built it locally (on the latest ergogen version, currently v4.1.0). The issue occurs on the demo and local version.
I've also tested this on the original GUI version by MvEerd, both the live demo at https://ergogen.cache.works/ and that version built locally. There, this problem doesn't seem to occur.

**Comment by ceoloide** [comment]
I'm actively looking into this, thanks for logging the issue.
